// Generates the 64×64 blue-noise threshold map used by the dithered photos
// (void-and-cluster, Ulichney 1993) and writes it to src/lib/blue-noise.ts.
// Run once with `node scripts/blue-noise.js`; the output is committed.
import { writeFile } from "node:fs/promises";

const N = 64;
const SIZE = N * N;
const SIGMA = 1.9;

// Toroidal Gaussian, so the tile repeats without seams.
const kernel = new Float64Array(SIZE);
for (let y = 0; y < N; y += 1) {
  for (let x = 0; x < N; x += 1) {
    const dx = Math.min(x, N - x);
    const dy = Math.min(y, N - y);
    kernel[y * N + x] = Math.exp(-(dx * dx + dy * dy) / (2 * SIGMA * SIGMA));
  }
}

// Deterministic PRNG so reruns produce the same file.
let seed = 0x5eed;
const random = () => {
  seed = (seed * 1664525 + 1013904223) >>> 0;
  return seed / 2 ** 32;
};

function makeEnergy(bits) {
  const energy = new Float64Array(SIZE);
  for (let i = 0; i < SIZE; i += 1) if (bits[i]) splat(energy, i, 1);
  return energy;
}

function splat(energy, index, sign) {
  const px = index % N;
  const py = (index / N) | 0;
  for (let y = 0; y < N; y += 1) {
    const row = ((y - py + N) % N) * N;
    for (let x = 0; x < N; x += 1) energy[y * N + x] += sign * kernel[row + ((x - px + N) % N)];
  }
}

function extreme(energy, bits, want, pickMax) {
  let best = -1;
  let value = pickMax ? -Infinity : Infinity;
  for (let i = 0; i < SIZE; i += 1) {
    if (bits[i] !== want) continue;
    if (pickMax ? energy[i] > value : energy[i] < value) {
      value = energy[i];
      best = i;
    }
  }
  return best;
}

// Phase 0: an evenly spread initial pattern.
const initial = new Uint8Array(SIZE);
const ones = Math.round(SIZE * 0.1);
for (let placed = 0; placed < ones;) {
  const i = Math.floor(random() * SIZE);
  if (!initial[i]) {
    initial[i] = 1;
    placed += 1;
  }
}
let energy = makeEnergy(initial);
for (;;) {
  const cluster = extreme(energy, initial, 1, true);
  initial[cluster] = 0;
  splat(energy, cluster, -1);
  const voidIndex = extreme(energy, initial, 0, false);
  if (voidIndex === cluster) {
    initial[cluster] = 1;
    splat(energy, cluster, 1);
    break;
  }
  initial[voidIndex] = 1;
  splat(energy, voidIndex, 1);
}

const rank = new Uint32Array(SIZE);

// Phase 1: rank the initial points by removing the tightest cluster.
{
  const bits = initial.slice();
  const e = makeEnergy(bits);
  for (let r = ones - 1; r >= 0; r -= 1) {
    const cluster = extreme(e, bits, 1, true);
    bits[cluster] = 0;
    splat(e, cluster, -1);
    rank[cluster] = r;
  }
}

// Phases 2 and 3: fill the largest void until every cell has a rank.
{
  const bits = initial.slice();
  const e = makeEnergy(bits);
  for (let r = ones; r < SIZE; r += 1) {
    const voidIndex = extreme(e, bits, 0, false);
    bits[voidIndex] = 1;
    splat(e, voidIndex, 1);
    rank[voidIndex] = r;
  }
}

const bytes = Buffer.from(Array.from(rank, (r) => Math.floor((r * 256) / SIZE)));
await writeFile(
  new URL("../src/lib/blue-noise.ts", import.meta.url),
  `// Generated by scripts/blue-noise.js. 64×64 blue-noise thresholds, 0–255.
export const BLUE_NOISE_SIZE = ${N};

const encoded =
  "${bytes.toString("base64")}";

let decoded: Uint8Array | undefined;

export function blueNoise() {
  decoded ??= Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0));
  return decoded;
}
`,
);
console.log("wrote src/lib/blue-noise.ts");
